/*You are given three positive integers num1, num2, and num3.

The key of num1, num2, and num3 is defined as a four-digit number such that:

Initially, if any number has less than four digits, it is padded with leading zeros.
The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
Return the key of the three numbers without leading zeros (if any).

 

Example 1:

Input: num1 = 1, num2 = 10, num3 = 1000

Output: 0

Explanation:

On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".

The 1st digit of the key is min(0, 0, 1).
The 2nd digit of the key is min(0, 0, 0).
The 3rd digit of the key is min(0, 1, 0).
The 4th digit of the key is min(1, 0, 0).
Hence, the key is "0000", i.e. 0.

Example 2:

Input: num1 = 987, num2 = 879, num3 = 798

Output: 777

Example 3:

Input: num1 = 1, num2 = 2, num3 = 3

Output: 1

 

Constraints:

1 <= num1, num2, num3 <= 9999*/

class Solution {
public:
    int min3(int a,int b,int c)
    {
        if(a<=c && a<=b) return a;
        if(b<=a &&b<=c) return b;
        if(c<=a&& c<=b) return c;
        return c;
    }
    int generateKey(int num1, int num2, int num3) {
        vector<int> digits1;
        vector<int> digits2;
        vector<int> digits3;
        while (num1 > 0) {
            int digit = num1 % 10;
            digits1.push_back(digit);
            num1 = num1 / 10;
        }
        while (num2 > 0) {
            int digit = num2 % 10;
            digits2.push_back(digit);
            num2 = num2 / 10;
        }
        while (num3 > 0) {
            int digit = num3 % 10;
            digits3.push_back(digit);
            num3 = num3 / 10;
        }
        while (digits1.size() < 4) {
            digits1.push_back(0);
        }
        while (digits2.size() < 4) {
            digits2.push_back(0);
        }
        while (digits3.size() < 4) {
            digits3.push_back(0);
        }
        int key=0;
        for(int i=0;i<4;i++)
        {
            cout<<digits1[i]<<" "<<digits2[i]<<" "<<digits3[i]<<endl;
            key+=min3(digits1[i],digits2[i],digits3[i])*pow(10,i);
            cout<<"min "<<min3(digits1[i],digits2[i],digits3[i])<<endl;
        }
        return key;
    }
};